Adding endpoint to render main navigation html
creativecommons/wp-theme-creativecommons.org pull request #18
Opened 2021-11-22 17:00 UTC by shailee-m

## Fixes
Related To https://github.com/creativecommons/project_creativecommons.org/issues/56 by @brylie 

## Checklist
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-11-22 17:02 UTC, shailee-m commented
CC: @brylie

2021-11-23 06:58 UTC, brylie requested changes

2021-11-23 06:58 UTC, brylie commented on endpoints/menu/menu_endpoints.php
> +    return $html_string . " <style> @import url(https://unpkg.com/@creativecommons/fonts@2020.9.3/css/fonts.css); @import url(https://creativecommons.org/wp-content/themes/creativecommons-base/assets
If possible, we should avoid hard-coding the creativecommons.org domain or version number here. We always want to serve the latest version of the CSS.
```suggestion
    return $html_string . " <style> @import url(https://unpkg.com/@creativecommons/fonts@2020.9.3/css/fonts.css); @import url(https://creativecommons.org/wp-content/themes/creativecommons-base/assets/css/styles.css); </style> ";
```

2021-11-23 19:12 UTC, shailee-m commented on endpoints/menu/menu_endpoints.php
> +    return $html_string . " <style> @import url(https://unpkg.com/@creativecommons/fonts@2020.9.3/css/fonts.css); @import url(https://creativecommons.org/wp-content/themes/creativecommons-base/assets
actually, `https://creativecommons.org/wp-content/themes/creativecommons-base/assets/css/styles.css` doesn't render anything at all. Locally, I am using localhost:8080 to render the CSS. I was waiting for the CDN discussion to resolve

2021-11-30 05:22 UTC, MuluhGodson commented on endpoints/menu/menu_endpoints.php
> +    return $html_string . " <style> @import url(https://unpkg.com/@creativecommons/fonts@2020.9.3/css/fonts.css); @import url(https://creativecommons.org/wp-content/themes/creativecommons-base/assets
> actually, https://creativecommons.org/wp-content/themes/creativecommons-base/assets/css/styles.css doesn't render > anything at all. Locally, I am using localhost:8080 to render the CSS. I was waiting for the CDN discussion to resolve



This issue:
- [x] https://github.com/creativecommons/project_creativecommons.org/issues/171 made the files in the `assets` folder of both `creativecommons-base` and `wp-creativecommons.org` to be obsolete.

2021-11-30 09:26 UTC, brylie requested changes

2021-11-30 09:26 UTC, brylie commented on endpoints/menu/menu_endpoints.php
> +        "@import url(http://localhost:8080/wp-content/themes/creativecommons-base/assets/css/styles.css); "
We can get the site URL from WordPress using the [get_site_url()](https://developer.wordpress.org/reference/functions/get_site_url/) function. That way, we don't need to hard-code the URL component here.

2021-11-30 09:28 UTC, brylie commented on endpoints/menu/menu_endpoints.php
> +        "@import url(http://localhost:8080/wp-content/themes/creativecommons-base/assets/css/styles.css); "
Also, we no longer use the `assets` directory in the theme project.

2021-12-03 13:48 UTC, closed without merging