Inital theme.json with custom padding settins
creativecommons/wp-theme-creativecommons.org pull request #19
Opened 2021-11-23 11:31 UTC by MuluhGodson

## Fixes

Fixes https://github.com/creativecommons/project_creativecommons.org/issues/121 by @brylie 

## Description
The `theme.json` file works as from WordPress v5.8
While the padding works as expected, the margins panels don't show up.
## Screenshots
![image](https://user-images.githubusercontent.com/40151808/143016649-03a890e2-5212-4cf9-8867-53fbf44e167a.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-11-24 07:48 UTC, brylie commented
Having the padding panels is already a good move :-)

2021-11-24 07:48 UTC, brylie commented
Let me know when this is ready for review.

2021-11-24 23:25 UTC, MuluhGodson commented
I erroneously converted this PR from Draft to Ready. 
I wish to indicate that it should still be regarded as being in DRAFT as there are some things to iron out.

2021-11-25 08:55 UTC, brylie requested changes

2021-11-25 08:55 UTC, brylie commented on custom-block-settings.js
> +};
This is still *procedural* code, just JavaScript this time. Let's try to keep the theme configuration *declarative*, even though it may seem more verbose.

2021-11-25 09:00 UTC, brylie commented on custom-block-settings.js
> +};
We can follow the [theme.json example given by @ramonjd](https://github.com/WordPress/gutenberg/pull/34630#issuecomment-977658439), which is what your code essentially produces. I'm just saying we should create the configuration structure manually rather than in a procedural loop.

```js
"blocks": {
    "core/group": {
        "spacing": {
            "blockGap": true,
            "margin": true,
            "padding": true,
            "units": [ "px", "em", "rem", "vh", "vw", "%" ]
        },
    }
}
```

2021-11-25 17:41 UTC, MuluhGodson commented on custom-block-settings.js
> +};
The reason for the javascript was to because the blocks by default don't opt for custom margins, so specifying in the `theme.json` file doesn't work if the block itself doesn't opt for the specific setting. 
I logged the `column` block settings and as you can see it supports only `customPaddings` by default (which explains why earlier just the padding controls were displayed and not the margin controls.)

Core/Column default spacing settings
![image](https://user-images.githubusercontent.com/40151808/143483269-69c2625f-3224-4fe4-aea8-8a061a92f2e8.png)


Adding custom margin support via Block Supports API
![image](https://user-images.githubusercontent.com/40151808/143483431-6f1bdd8b-0694-4687-a5a3-9229f3c5d6f0.png)

With this, when we declare support for margins and paddings in the `theme.json` file they will be applied to the blocks since the blocks now opt for them.

from @ramonjd 
>Enabling margin and padding globally via theme.json will "enable" margin and padding to be used so long as the block opts into them using the "supports" object. More info [here](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#spacing) on that.


>I'm just saying we should create the configuration structure declaratively rather than in a procedural loop.
The reason for using a loop was to limit the custom spacing to the 3 blocks (`group`, `columns` and `column`), else the custom margin and padding controls will be applied to all blocks (paragraphs, images etc)

2021-11-26 01:32 UTC, MuluhGodson commented on custom-block-settings.js
> +};
More on this: The last paragraph on this link: https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#settings

>Note, however, that not all settings are relevant for all blocks. The settings section provides an opt-in/opt-out mechanism for themes, but it’s the block’s responsibility to add support for the features that are relevant to it. For example, if a block doesn’t implement the dropCap feature, a theme can’t enable it for such a block through theme.json.

2021-11-26 01:41 UTC, MuluhGodson commented on custom-block-settings.js
> +};
On wordpress core: cheking the `block.json` file for the (group and column block) indicates:

- `core/column` : https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks/column/block.json#L32
- `core/group`: https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks/group/block.json#L28

This should explain why padding controls work just by declaring them in the `theme.json` but margin controls don't.

2021-11-26 01:59 UTC, MuluhGodson commented on custom-block-settings.js
> +};
I just found this active discussion on the WP repository: 
- [ ] https://github.com/WordPress/gutenberg/issues/35114

2021-11-26 10:20 UTC, brylie commented on custom-block-settings.js
> +};
OK, so should we keep the imperative code for now?

2021-11-26 10:21 UTC, brylie approved these changes

2021-11-26 10:22 UTC, brylie commented
It looks like there is still a minor conflict in functions.php

2021-11-26 10:41 UTC, MuluhGodson commented on custom-block-settings.js
> +};
Yeah u think for now this is better. 
I will keep checking upstream especially the conversation I referenced above. On the case the `theme.json` file is updated to be able to opt settings for blocks and enforce them I will open a new issue and add a follow up PR so that we can then use the declarative approach.

2021-11-26 11:12 UTC, merged