[#132] convert json based API to HTML returning api
creativecommons/wp-theme-creativecommons.org pull request #21
Opened 2021-11-25 17:02 UTC by shailee-m

## Fixes
Related to https://github.com/creativecommons/project_creativecommons.org/issues/132 by @brylie 

## Description
Replaced API functions that return JSON with HTML content generation logic. Currently, using the walker class to generate the HTML. Can also use twig here if custom HTML output is required.

## Checklist
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

2021-11-26 08:57 UTC, brylie requested changes

2021-11-26 08:57 UTC, brylie commented on inc/filters.php
> +      "@import url(http://127.0.0.1:8000/wp-content/themes/creativecommons-base/assets/css/styles.css);"
We can get the site URL via WordPress [`get_site_url`](https://developer.wordpress.org/reference/functions/get_site_url/)

2021-11-26 10:22 UTC, brylie commented
For what it's worth, we might not want to remove the JSON endpoints. The original task is just to add HTML endpoints.

2021-11-27 07:01 UTC, shailee-m commented
Closing this PR as we are looking into vue components

2021-11-27 07:01 UTC, closed without merging

2021-11-30 09:21 UTC, brylie commented
@shailee-m, would you like to create a Vue component that fetches and renders the WordPress navigation menu?